server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    #git.mode: full
  endpoint:
    shutdown:
      enabled: true
    health:
      #show-details: always
      show-components: always
  endpoints:
    web:
      #base-path: "/manage"
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: jj

logging:
  level:
    hello.controller: debug
